title: PKP Documentation Hub
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-readme-index
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "book"
  -
    scope:
      path: "dev/api"
      type: "pages"
    values:
      swaggerUiVersion: 3
url: "https://docs.pkp.sfu.ca" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
